name: Release
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: zip -r ./${{github.repository}}.zip module.json lang/ scripts/ styles/ templates/ css/

    # Create a release for this specific version
      - name: Update Release with Files
        id: create_version_release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          name: ${{ github.event.release.name }}
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "./module.json, ./${{github.repository}}.zip"
          tag: ${{ github.event.release.tag_name }}
          body: ${{ github.event.release.body }}

