name: Release

on:
  push:
    tags:
     - v*

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - run: zip -r ./spell-list.zip module.json lang/ scripts/ templates/ css/ svg/ README.md LICENSE

    # Create a release for this specific version
      - name: Update Release with Files
        id: create_version_release
        uses: ncipollo/release-action@v1
        with:
          artifacts: ./module.json, ./spell-list.zip

